### ISSUE TITLE
Multi-view registration method

### ISSUE THREAD

**Issue by BIGROOKIE24** [fiji/SPIM_Registration#135]
Hi,

I wonder if this bead registration method can be used to register 3d point cloud. Using the 3d points as input directly without extracting the beads coordinates, if this method could work.? By the way, how to compile this SPIM_Registration source code with Eclipse? It seems some files are missing and many errors occurred when the the code was compiled. 

Look forward to your nice reply. Thank you!

**Comment by StephanPreibisch** [comment]
Hi,

you should use BigStitcher and the multi view-reconstruction, which are the current version, they are linked in the project description (Deprecated, instead check out: https://github.com/preibischLab/multiview-reconstruction & https://github.com/PreibischLab/BigStitcher).

It can deal with point clouds, the easiest way is to check out the headless package and interest point registration, you can easily feed in just points.

You need to import it as existing Maven project, then everything works fine since the build process is based on Maven.

All the best,
Stephan
